language: python

python:
  - "3.8"

notifications:
  email: false

os:
  - linux

jobs:
  include:
    # perform a linux build
    - services: docker
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64
    # perform a linux PPC64LE build
    - services: docker
      arch: ppc64le
    # perform a linux S390X build
    - services: docker
      arch: s390x
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.8.6
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  # pandoc
  - sudo apt-get -y install pandoc
  # anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda config --add channels pypi
  - conda info -a
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" pip
  - source activate test-environment
  - pip install pytest travis-sphinx
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install -e ".[test,docs]"
  - python3 -m pip install cibuildwheel==2.12.1

script:
  - pytest -v -s
  - travis-sphinx build --source=docs
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  - travis-sphinx deploy
